
exports.seed = function (knex, Promise) {
  // Deletes ALL existing entries
  return knex('books').del()
    .then(function () {
      // Inserts seed entries
      return knex('books').insert([
        { isbn: "0-330-49286-1", title: "The Shape of Water", theme1: 'Police Procedural', theme2: '-', genre1: 'Crime Novel', genre2: 'Mystery Novel', date: '10-03-1994', recommended: true, price: '6.80', status: 'available', sold: 100, descr:"Silvio Luparello, an engineer, developer, and aspiring politician from an aristocratic construction family, dies of a heart attack while having sex with his nephew and lover Giorgio at his beach house. The nephew panics, and, wanting to protect his uncle from the embarrassing circumstance of his death and not trusting himself to be able to move his uncle's body due to his epilepsy, calls his uncle's friend and political crony Attorney Rizzo for help...." },
        { isbn: '0-330-49291-8', title: 'The Terracotta Dog', theme1: 'Police Procedural', theme2: '-', genre1: 'Crime Novel', genre2: 'Mystery Novel', date: '18-04-1996', recommended: false, price: '6.80', status: 'available', sold: 90, descr: "The story starts off with 'Tano Il Greco', a tired mafia boss, making a deal with Montalbano to stage his arrest in order for him to save face. The arrest causes Montalbano to have to appear at a press conference and be considered for promotion, both of which he does not appreciate. At the same time there has also been a seemingly unrelated and mysterious theft of a grocery store delivery truck; the truck is discovered the next morning, abandoned, with the stolen goods still within and intact."  },
        { isbn: '0-7475-3269-9', title: "Harry Potter and the Philosopher's Stone", theme1: 'Magic', theme2: 'Teenagers', genre1: 'Fantasy Novel', genre2: 'Young Adult Novel', date: '26-06-1997', recommended: false, price: '8.50', status: 'available', sold: 300, descr:"Harry Potter and the Philosopher's Stone is a fantasy novel written by British author J. K. Rowling. The first novel in the Harry Potter series and Rowling's debut novel, it follows Harry Potter, a young wizard who discovers his magical heritage on his eleventh birthday, when he receives a letter of acceptance to Hogwarts School of Witchcraft and Wizardry. Harry makes close friends and a few enemies during his first year at the school, and with the help of his friends, Harry faces an attempted comeback by the dark wizard Lord Voldemort, who killed Harry's parents, but failed to kill Harry when he was just 15 months old." },
        { isbn: '0-7475-3849-2', title: 'Harry Potter and the Chamber of Secrets', theme1: 'Magic', theme2: 'Teenagers', genre1: 'Fantasy Novel', genre2: 'Young Adult Novel', date: '02-07-1998', recommended: false, price: '8.50', status: 'available', sold: 270, descr:"Harry Potter and the Chamber of Secrets is a fantasy novel written by British author J. K. Rowling and the second novel in the Harry Potter series. The plot follows Harry's second year at Hogwarts School of Witchcraft and Wizardry, during which a series of messages on the walls of the school's corridors warn that the 'Chamber of Secrets' has been opened and that the 'heir of Slytherin' would kill all pupils who do not come from all-magical families. These threats are found after attacks which leave residents of the school petrified. Throughout the year, Harry and his friends Ron and Hermione investigate the attacks."  },
        { isbn: '0-486-29256-8', title: 'Wuthering Heights', theme1: 'Love', theme2: 'Revenge', genre1: 'Tragedy', genre2: 'Gothic Novel', date: '12-1847', recommended: true, price: '5.90', status: 'available', sold: 230, descr: "Wuthering Heights, Emily Brontë's only novel, was published in 1847 under the pseudonym 'Ellis Bell'. It was written between October 1845 and June 1846. Wuthering Heights and Anne Brontë's Agnes Grey were accepted by publisher Thomas Newby before the success of their sister Charlotte's novel Jane Eyre. After Emily's death, Charlotte edited the manuscript of Wuthering Heights and arranged for the edited version to be published as a posthumous second edition in 1850." },
        { isbn: '0-358-31746-2', title: 'Pride and Prejudice', theme1: 'Love', theme2: 'Class', genre1: 'Romantic Novel', genre2: 'Historical Fiction', date: '28-01-1813', recommended: true, price: '7.40', status: 'available', sold: 250, descr:"Pride and Prejudice is an 1813 romantic novel of manners written by Jane Austen. The novel follows the character development of Elizabeth Bennet, the dynamic protagonist of the book, who learns about the repercussions of hasty judgments and eventually comes to appreciate the difference between superficial goodness and actual goodness. A classic piece filled with comedy, its humor lies in its honest depiction of manners, education, marriage and money during the Regency era in Great Britain."  },
        { isbn: '0-684-19723-7', title: 'The Picture of Dorian Gray', theme1: 'Aestheticism', theme2: 'Duplicity', genre1: 'Phylosophical Fiction', genre2: 'Decadent Literature', date: '07-1890', recommended: true, price: '7.90', status: 'available', sold: 280, descr:"The Picture of Dorian Gray is a Gothic and philosophical novel by Oscar Wilde, first published complete in the July 1890 issue of Lippincott's Monthly Magazine.[1][2] Fearing the story was indecent, the magazine's editor deleted roughly five hundred words before publication without Wilde's knowledge. Despite that censorship, The Picture of Dorian Gray offended the moral sensibilities of British book reviewers, some of whom said that Oscar Wilde merited prosecution for violating the laws guarding public morality. In response, Wilde aggressively defended his novel and art in correspondence with the British press, although he personally made excisions of some of the most controversial material when revising and lengthening the story for book publication the following year."  },
        { isbn: '0-9123-2134-2', title: 'Tiny Pretty Things', theme1: 'Discrimination', theme2: 'Mystery', genre1: 'Young Adult Novel', genre2: 'Contemporary', date: '26-05-2015', recommended: false, price: '9.90', status: 'available', sold: 100, descr: "Black Swan meets Pretty Little Liars in this soapy, drama-packed novel featuring diverse characters who will do anything to be the prima at their elite ballet school. Gigi, Bette, and June, three top students at an exclusive Manhattan ballet school, have seen their fair share of drama. Free-spirited new girl Gigi just wants to dance—but the very act might kill her. Privileged New Yorker Bette's desire to escape the shadow of her ballet-star sister brings out a dangerous edge in her. And perfectionist June needs to land a lead role this year or her controlling mother will put an end to her dancing dreams forever." }
      ]);
    });
};
